name: PlayerList
main: Xtra.PlayerList.PlayerList
version: 1.1.0
commands:
  players:
    description: Gives a list of players in your world.
    aliases: players
    usage: /players [world | "all"]
  phide:
    description: Hides player.
    aliases: phide
    usage: /phide
  pshow:
    description: Show's player.
    aliases: pshow
    usage: /pshow